apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: customermanagementapi
    version: "1.0"
  name: customermanagementapi-v1
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: customermanagementapi
      version: "1.0"
  template:
    metadata:
      labels:
        system: pitstop
        app: customermanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: docker.pkg.github.com/bravecobra/pitstop/customermanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: customermanagementapi
        ports:
        - containerPort: 5100
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
