apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: invoiceservice
    version: "1.0"
  name: invoiceservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: invoiceservice
  template:
    metadata:
      labels:
        system: pitstop
        app: invoiceservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: docker.pkg.github.com/bravecobra/pitstop/invoiceservice:1.0
        imagePullPolicy: IfNotPresent
        name: invoiceservice
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
