apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: notificationservice
    version: "1.0"
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: notificationservice
  template:
    metadata:
      labels:
        system: pitstop
        app: notificationservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: docker.pkg.github.com/bravecobra/pitstop/notificationservice:1.0
        imagePullPolicy: IfNotPresent
        name: notificationservice
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
