apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: timeservice
    version: "1.0"
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: timeservice
  template:
    metadata:
      labels:
        system: pitstop
        app: timeservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: docker.pkg.github.com/bravecobra/pitstop/timeservice:1.0
        imagePullPolicy: IfNotPresent
        name: timeservice
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
