apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: workshopmanagementeventhandler
    version: "1.0"
  name: workshopmanagementeventhandler
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      system: pitstop
      app: workshopmanagementeventhandler
  template:
    metadata:
      labels:
        system: pitstop
        app: workshopmanagementeventhandler
        version: "1.0"
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: docker.pkg.github.com/bravecobra/pitstop/workshopmanagementeventhandler:1.0
        imagePullPolicy: IfNotPresent
        name: workshopmanagementeventhandler
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
