docker push docker.pkg.github.com/bravecobra/pitstop/customermanagementapi:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/customermanagementapi:2.0
docker push docker.pkg.github.com/bravecobra/pitstop/webapp:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/workshopmanagementeventhandler:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/timeservice:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/notificationservice:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/invoiceservice:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/auditlogservice:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/workshopmanagementapi:1.0
docker push docker.pkg.github.com/bravecobra/pitstop/vehiclemanagementapi:1.0